import json
import sys

# Set UTF-8 encoding
sys.stdout.reconfigure(encoding="utf-8")

# Load the notebook
with open("08_advanced_oscillators.ipynb", "r", encoding="utf-8") as f:
    nb = json.load(f)

# Define cells to add
cells_to_add = [
    # Data Fetching
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Fetch 1 year of data for UUE Holdings Berhad\\n",
            'ticker = "0310.KL"  # UUE Holdings\\n',
            'print(f"Fetching data for {ticker}...\\\\n")\\n',
            "\\n",
            "try:\\n",
            '    data = yf.download(ticker, period="1y", progress=False)\\n',
            "    \\n",
            "    # Flatten column names if MultiIndex\\n",
            "    if isinstance(data.columns, pd.MultiIndex):\\n",
            "        data.columns = data.columns.get_level_values(0)\\n",
            "    \\n",
            "    if data.empty:\\n",
            '        print("No data received.")\\n',
            "    else:\\n",
            '        print(f"Successfully fetched {len(data)} days of data!")\\n',
            '        print(f"Date range: {data.index[0].date()} to {data.index[-1].date()}")\\n',
            "        print(f\"Latest close: RM {data['Close'].iloc[-1]:.2f}\\\\n\")\\n",
            "        print(data.head())\\n",
            "except Exception as e:\\n",
            '    print(f"Error: {e}")',
        ],
        "outputs": [],
        "execution_count": None,
    },
    # Stochastic Theory
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\\n",
            "\\n",
            "## Part 3: The Stochastic Oscillator\\n",
            "\\n",
            "### What is the Stochastic Oscillator?\\n",
            "\\n",
            "Created by George Lane in the 1950s, the **Stochastic Oscillator** compares a stock's closing price to its price range over a period.\\n",
            "\\n",
            "**Formula**:\\n",
            "- **%K** = (Current Close - Lowest Low) / (Highest High - Lowest Low) × 100\\n",
            "- **%D** = 3-day SMA of %K (signal line)\\n",
            "\\n",
            "**Default Settings**: 14, 3, 3\\n",
            "- 14 = Look-back period\\n",
            "- 3 = %K smoothing\\n",
            "- 3 = %D smoothing\\n",
            "\\n",
            "### Interpretation\\n",
            "\\n",
            "**Range**: 0 to 100\\n",
            "- **Above 80** = Overbought (potential sell)\\n",
            "- **Below 20** = Oversold (potential buy)\\n",
            "- **%K crosses above %D** = Bullish signal\\n",
            "- **%K crosses below %D** = Bearish signal\\n",
            "\\n",
            "### Real-World Analogy\\n",
            "\\n",
            "Think of Stochastic like **room temperature**:\\n",
            "- Value of 20 = Very cold (stock oversold, may heat up)\\n",
            "- Value of 80 = Very hot (stock overbought, may cool down)\\n",
            "- Value of 50 = Comfortable (neutral zone)\\n",
            "\\n",
            "---",
        ],
    },
    # Stochastic Calculation
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Calculate Stochastic Oscillator manually\\n",
            "if 'data' in locals() and not data.empty:\\n",
            "    period = 14\\n",
            "    smooth_k = 3\\n",
            "    smooth_d = 3\\n",
            "    \\n",
            "    # Calculate %K (fast stochastic)\\n",
            "    lowest_low = data['Low'].rolling(window=period).min()\\n",
            "    highest_high = data['High'].rolling(window=period).max()\\n",
            "    \\n",
            "    data['Stoch_K'] = ((data['Close'] - lowest_low) / (highest_high - lowest_low)) * 100\\n",
            "    \\n",
            "    # Smooth %K to get slow stochastic\\n",
            "    data['Stoch_K'] = data['Stoch_K'].rolling(window=smooth_k).mean()\\n",
            "    \\n",
            "    # Calculate %D (signal line)\\n",
            "    data['Stoch_D'] = data['Stoch_K'].rolling(window=smooth_d).mean()\\n",
            "    \\n",
            '    print("Stochastic Oscillator calculated successfully!\\\\n")\\n',
            '    print("Last 5 days:")\\n',
            "    print(data[['Close', 'Stoch_K', 'Stoch_D']].tail())\\n",
            "    \\n",
            "    # Current reading\\n",
            "    latest_k = data['Stoch_K'].iloc[-1]\\n",
            "    latest_d = data['Stoch_D'].iloc[-1]\\n",
            "    \\n",
            '    print(f"\\\\nCurrent Stochastic:")\\n',
            '    print(f"%K: {latest_k:.2f}")\\n',
            '    print(f"%D: {latest_d:.2f}")\\n',
            "    \\n",
            "    if latest_k > 80:\\n",
            '        print("\\\\nOVERBOUGHT condition - Consider selling")\\n',
            "    elif latest_k < 20:\\n",
            '        print("\\\\nOVERSOLD condition - Consider buying")\\n',
            "    else:\\n",
            '        print("\\\\nNEUTRAL condition")\\n',
            "else:\\n",
            '    print("Please run data fetching cell first!")',
        ],
        "outputs": [],
        "execution_count": None,
    },
    # Williams %R Theory
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\\n",
            "\\n",
            "## Part 4: Williams %R\\n",
            "\\n",
            "### What is Williams %R?\\n",
            "\\n",
            "Developed by Larry Williams, **Williams %R** measures overbought/oversold levels. It's similar to Stochastic but:\\n",
            "- Range: 0 to -100 (inverted scale)\\n",
            "- More sensitive (faster signals)\\n",
            "- Single line (no %D)\\n",
            "\\n",
            "**Formula**:\\n",
            "Williams %R = [(Highest High - Current Close) / (Highest High - Lowest Low)] × -100\\n",
            "\\n",
            "**Default Period**: 14 days\\n",
            "\\n",
            "### Interpretation\\n",
            "\\n",
            "**Range**: 0 to -100\\n",
            "- **Above -20** = Overbought (potential sell)\\n",
            "- **Below -80** = Oversold (potential buy)\\n",
            "- **-50** = Neutral zone\\n",
            "\\n",
            "### Williams %R vs Stochastic\\n",
            "\\n",
            "| Feature | Williams %R | Stochastic |\\n",
            "|---------|-------------|------------|\\n",
            "| **Lines** | 1 line | 2 lines (%K + %D) |\\n",
            "| **Scale** | 0 to -100 | 0 to 100 |\\n",
            "| **Speed** | Faster, more sensitive | Slower, more smooth |\\n",
            "| **Best For** | Early signals | Confirmed signals |\\n",
            "\\n",
            "### Key Insight\\n",
            "\\n",
            "Use Williams %R to **spot** potential reversals early, then wait for Stochastic to **confirm** them!\\n",
            "\\n",
            "---",
        ],
    },
    # Williams %R Calculation
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Calculate Williams %R\\n",
            "if 'data' in locals() and not data.empty:\\n",
            "    period = 14\\n",
            "    \\n",
            "    # Calculate Williams %R\\n",
            "    highest_high = data['High'].rolling(window=period).max()\\n",
            "    lowest_low = data['Low'].rolling(window=period).min()\\n",
            "    \\n",
            "    data['Williams_R'] = ((highest_high - data['Close']) / (highest_high - lowest_low)) * -100\\n",
            "    \\n",
            '    print("Williams %R calculated successfully!\\\\n")\\n',
            '    print("Last 5 days:")\\n',
            "    print(data[['Close', 'Williams_R']].tail())\\n",
            "    \\n",
            "    # Current reading\\n",
            "    latest_wr = data['Williams_R'].iloc[-1]\\n",
            "    \\n",
            '    print(f"\\\\nCurrent Williams %R: {latest_wr:.2f}")\\n',
            "    \\n",
            "    if latest_wr > -20:\\n",
            '        print("OVERBOUGHT - Above -20")\\n',
            "    elif latest_wr < -80:\\n",
            '        print("OVERSOLD - Below -80")\\n',
            "    else:\\n",
            '        print("NEUTRAL - Between -20 and -80")\\n',
            "else:\\n",
            '    print("Please run data fetching cell first!")',
        ],
        "outputs": [],
        "execution_count": None,
    },
    # Visualization
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Create comprehensive oscillator chart\\n",
            "if 'data' in locals() and not data.empty and 'Stoch_K' in data.columns:\\n",
            "    recent_data = data.tail(120)\\n",
            "    \\n",
            "    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(15, 12), sharex=True)\\n",
            "    \\n",
            "    # Price chart\\n",
            "    ax1.plot(recent_data.index, recent_data['Close'], label='Close Price', linewidth=2, color='black')\\n",
            "    ax1.set_ylabel('Price (RM)', fontsize=12)\\n",
            "    ax1.set_title(f'{ticker} - Price with Oscillators', fontsize=16, fontweight='bold')\\n",
            "    ax1.legend(loc='best')\\n",
            "    ax1.grid(True, alpha=0.3)\\n",
            "    \\n",
            "    # Stochastic\\n",
            "    ax2.plot(recent_data.index, recent_data['Stoch_K'], label='%K', linewidth=2, color='blue')\\n",
            "    ax2.plot(recent_data.index, recent_data['Stoch_D'], label='%D', linewidth=2, color='red')\\n",
            "    ax2.axhline(y=80, color='r', linestyle='--', alpha=0.5, label='Overbought (80)')\\n",
            "    ax2.axhline(y=20, color='g', linestyle='--', alpha=0.5, label='Oversold (20)')\\n",
            "    ax2.fill_between(recent_data.index, 80, 100, alpha=0.1, color='red')\\n",
            "    ax2.fill_between(recent_data.index, 0, 20, alpha=0.1, color='green')\\n",
            "    ax2.set_ylabel('Stochastic', fontsize=12)\\n",
            "    ax2.set_ylim(0, 100)\\n",
            "    ax2.legend(loc='best')\\n",
            "    ax2.grid(True, alpha=0.3)\\n",
            "    \\n",
            "    # Williams %R\\n",
            "    ax3.plot(recent_data.index, recent_data['Williams_R'], label='Williams %R', linewidth=2, color='purple')\\n",
            "    ax3.axhline(y=-20, color='r', linestyle='--', alpha=0.5, label='Overbought (-20)')\\n",
            "    ax3.axhline(y=-80, color='g', linestyle='--', alpha=0.5, label='Oversold (-80)')\\n",
            "    ax3.fill_between(recent_data.index, -20, 0, alpha=0.1, color='red')\\n",
            "    ax3.fill_between(recent_data.index, -100, -80, alpha=0.1, color='green')\\n",
            "    ax3.set_ylabel('Williams %R', fontsize=12)\\n",
            "    ax3.set_xlabel('Date', fontsize=12)\\n",
            "    ax3.set_ylim(-100, 0)\\n",
            "    ax3.legend(loc='best')\\n",
            "    ax3.grid(True, alpha=0.3)\\n",
            "    \\n",
            "    plt.tight_layout()\\n",
            "    plt.show()\\n",
            "    \\n",
            '    print("\\\\nChart shows price with both oscillators for comparison")\\n',
            "else:\\n",
            '    print("Please run calculation cells first!")',
        ],
        "outputs": [],
        "execution_count": None,
    },
    # Trading Strategy
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\\n",
            "\\n",
            "## Part 5: Trading Strategies with Oscillators\\n",
            "\\n",
            "### Strategy 1: Double Confirmation\\n",
            "\\n",
            "**Rules**:\\n",
            "1. Wait for BOTH oscillators to agree\\n",
            "2. Stochastic < 20 AND Williams %R < -80 → BUY signal\\n",
            "3. Stochastic > 80 AND Williams %R > -20 → SELL signal\\n",
            "4. Exit when either oscillator reaches opposite extreme\\n",
            "\\n",
            "**Strength**: Very reliable, few false signals\\n",
            "**Weakness**: Slower, may miss some moves\\n",
            "\\n",
            "### Strategy 2: Stochastic Crossover\\n",
            "\\n",
            "**Rules**:\\n",
            "1. Wait for %K to cross %D\\n",
            "2. %K crosses ABOVE %D while both < 20 → BUY\\n",
            "3. %K crosses BELOW %D while both > 80 → SELL\\n",
            "4. Place stop-loss 2-3% away\\n",
            "\\n",
            "**Strength**: Clear entry signals\\n",
            "**Weakness**: Can give false signals in strong trends\\n",
            "\\n",
            "### Strategy 3: Williams %R Early Entry\\n",
            "\\n",
            "**Rules**:\\n",
            "1. Use Williams %R for early entry\\n",
            "2. Williams %R < -80 → Prepare to buy\\n",
            "3. Wait for Williams %R to cross ABOVE -80 → BUY\\n",
            "4. Exit when Williams %R crosses ABOVE -20\\n",
            "\\n",
            "**Strength**: Catches moves early\\n",
            "**Weakness**: More false signals, needs tight stops\\n",
            "\\n",
            "---",
        ],
    },
    # Signal Detection
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Implement double confirmation strategy\\n",
            "if 'data' in locals() and not data.empty and 'Stoch_K' in data.columns:\\n",
            "    # Detect signals\\n",
            "    data['Buy_Signal'] = (data['Stoch_K'] < 20) & (data['Williams_R'] < -80)\\n",
            "    data['Sell_Signal'] = (data['Stoch_K'] > 80) & (data['Williams_R'] > -20)\\n",
            "    \\n",
            "    # Find recent signals\\n",
            "    recent_buys = data[data['Buy_Signal']].tail(5)\\n",
            "    recent_sells = data[data['Sell_Signal']].tail(5)\\n",
            "    \\n",
            '    print("Double Confirmation Strategy Signals\\\\n")\\n',
            '    print("="*60)\\n',
            "    \\n",
            '    print("\\\\nRecent BUY Signals (Both oversold):")\\n',
            "    if len(recent_buys) > 0:\\n",
            "        print(recent_buys[['Close', 'Stoch_K', 'Williams_R']].to_string())\\n",
            "    else:\\n",
            '        print("No recent buy signals")\\n',
            "    \\n",
            '    print("\\\\nRecent SELL Signals (Both overbought):")\\n',
            "    if len(recent_sells) > 0:\\n",
            "        print(recent_sells[['Close', 'Stoch_K', 'Williams_R']].to_string())\\n",
            "    else:\\n",
            '        print("No recent sell signals")\\n',
            "    \\n",
            "    # Current status\\n",
            '    print("\\\\n" + "="*60)\\n',
            '    print("CURRENT SETUP:")\\n',
            "    \\n",
            "    if data['Buy_Signal'].iloc[-1]:\\n",
            '        print("BUY SIGNAL - Both oscillators oversold!")\\n',
            "    elif data['Sell_Signal'].iloc[-1]:\\n",
            '        print("SELL SIGNAL - Both oscillators overbought!")\\n',
            "    else:\\n",
            '        print("NO SIGNAL - Wait for both oscillators to agree")\\n',
            "else:\\n",
            '    print("Please run calculation cells first!")',
        ],
        "outputs": [],
        "execution_count": None,
    },
    # Key Takeaways
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\\n",
            "\\n",
            "## Key Takeaways\\n",
            "\\n",
            "### What You Learned\\n",
            "\\n",
            "1. **Oscillators Basics**\\n",
            "   - Oscillators measure momentum in bounded range (0-100)\\n",
            "   - Best for identifying overbought/oversold conditions\\n",
            "   - Work better in ranging markets\\n",
            "\\n",
            "2. **Stochastic Oscillator**\\n",
            "   - Two lines: %K (fast) and %D (signal)\\n",
            "   - Above 80 = Overbought, Below 20 = Oversold\\n",
            "   - Crossovers provide trading signals\\n",
            "   - Default: 14, 3, 3\\n",
            "\\n",
            "3. **Williams %R**\\n",
            "   - Single line, inverted scale (0 to -100)\\n",
            "   - Above -20 = Overbought, Below -80 = Oversold\\n",
            "   - More sensitive than Stochastic\\n",
            "   - Good for early signals\\n",
            "\\n",
            "4. **Trading Strategies**\\n",
            "   - Double confirmation = Most reliable\\n",
            "   - Stochastic crossover = Clear signals\\n",
            "   - Williams %R early entry = Catches moves fast\\n",
            "\\n",
            "### Key Formulas\\n",
            "\\n",
            "**Stochastic**:\\n",
            "- %K = (Close - Lowest Low) / (Highest High - Lowest Low) × 100\\n",
            "- %D = 3-day SMA of %K\\n",
            "\\n",
            "**Williams %R**:\\n",
            "- Williams %R = [(Highest High - Close) / (Highest High - Lowest Low)] × -100\\n",
            "\\n",
            "---",
        ],
    },
    # Practice Exercises
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\\n",
            "\\n",
            "## Practice Exercises\\n",
            "\\n",
            "### Exercise 1: Oscillator Comparison\\n",
            "Look at the charts and answer:\\n",
            "1. When did Stochastic give false signals?\\n",
            "2. Did Williams %R signal earlier than Stochastic?\\n",
            "3. Which oscillator do you find easier to interpret?\\n",
            "\\n",
            "### Exercise 2: Try Different Stocks\\n",
            "Analyze different stocks and compare oscillator behavior:\\n",
            "- **1155.KL** (Maybank - large cap)\\n",
            "- **5296.KL** (Tenaga - utility)\\n",
            "\\n",
            "Questions:\\n",
            "1. Which stock shows more overbought/oversold signals?\\n",
            "2. Do oscillators work better on volatile or stable stocks?\\n",
            "\\n",
            "### Exercise 3: Backtest a Strategy\\n",
            "Choose the Double Confirmation strategy:\\n",
            "1. Find last 3 buy signals\\n",
            "2. Check what happened to price after each signal\\n",
            "3. Calculate win rate (how many were profitable?)\\n",
            "\\n",
            "---\\n",
            "\\n",
            "## What's Next?\\n",
            "\\n",
            "Congratulations on completing Module 08!\\n",
            "\\n",
            "**Next Module: Fibonacci Retracements & Support/Resistance Zones**\\n",
            "\\n",
            "In Module 09, you'll learn:\\n",
            "- Fibonacci retracement levels\\n",
            "- Support and resistance zones\\n",
            "- Combining Fibonacci with oscillators\\n",
            "- Entry and exit optimization\\n",
            "\\n",
            "**File**: `09_fibonacci_support_resistance.ipynb`\\n",
            "\\n",
            "---\\n",
            "\\n",
            "**Happy Trading! Always practice with paper money first!**",
        ],
    },
]

# Add cells to notebook
nb["cells"].extend(cells_to_add)

# Save the updated notebook
with open("08_advanced_oscillators.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Module 08 completed! Total cells: {len(nb['cells'])}")
