import json
import sys

sys.stdout.reconfigure(encoding="utf-8")

# Create Module 11: Advanced Chart Patterns & Trend Strength
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Module 11: Advanced Chart Patterns & Trend Strength\\n",
                "\\n",
                "---\\n",
                "\\n",
                "## Welcome to Module 11!\\n",
                "\\n",
                "Learn to identify powerful chart patterns that signal major price moves and measure trend strength!\\n",
                "\\n",
                "### Learning Objectives\\n",
                "\\n",
                "- Recognize continuation patterns (flags, pennants, triangles)\\n",
                "- Identify reversal patterns (head & shoulders, double tops/bottoms)\\n",
                "- Measure trend strength with ADX\\n",
                "- Combine patterns with trend strength\\n",
                "- Calculate pattern price targets\\n",
                "\\n",
                "### Prerequisites\\n",
                "\\n",
                "- Completed Modules 00-10\\n",
                "- Understanding of support/resistance\\n",
                "- Familiarity with trend analysis\\n",
                "\\n",
                "### Time Required: 75-90 minutes\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 1: Chart Pattern Basics\\n",
                "\\n",
                "### What are Chart Patterns?\\n",
                "\\n",
                "**Chart patterns** are recognizable shapes formed by price action that tend to lead to predictable outcomes.\\n",
                "\\n",
                "### Two Types of Patterns\\n",
                "\\n",
                "**1. Continuation Patterns** (trend continues):\\n",
                "- Flags\\n",
                "- Pennants\\n",
                "- Triangles (ascending, descending, symmetrical)\\n",
                "\\n",
                "**2. Reversal Patterns** (trend reverses):\\n",
                "- Head and Shoulders\\n",
                "- Double Top/Bottom\\n",
                "- Triple Top/Bottom\\n",
                "\\n",
                "### Why Patterns Work\\n",
                "\\n",
                "Patterns represent **collective psychology**:\\n",
                "- Accumulation phase (smart money buying)\\n",
                "- Distribution phase (smart money selling)\\n",
                "- Breakout phase (retail follows)\\n",
                "\\n",
                "### Real-World Analogy\\n",
                "\\n",
                "Chart patterns are like **traffic patterns**:\\n",
                "- **Flag/Pennant** = Rest stop on highway (brief pause before continuing)\\n",
                "- **Triangle** = Merging lanes (compression before expansion)\\n",
                "- **Head & Shoulders** = U-turn sign (complete direction reversal)\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Import libraries\\n",
                "import yfinance as yf\\n",
                "import pandas as pd\\n",
                "import numpy as np\\n",
                "import matplotlib.pyplot as plt\\n",
                "import seaborn as sns\\n",
                "import warnings\\n",
                "\\n",
                "warnings.filterwarnings('ignore')\\n",
                "%matplotlib inline\\n",
                "\\n",
                "try:\\n",
                "    plt.style.use('seaborn-v0_8-darkgrid')\\n",
                "except:\\n",
                "    try:\\n",
                "        plt.style.use('seaborn-darkgrid')\\n",
                "    except:\\n",
                "        plt.style.use('default')\\n",
                "\\n",
                'print("Libraries imported successfully!")',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Fetch data\\n",
                'ticker = "0310.KL"\\n',
                'print(f"Fetching {ticker}...")\\n',
                "\\n",
                'data = yf.download(ticker, period="1y", progress=False)\\n',
                "if isinstance(data.columns, pd.MultiIndex):\\n",
                "    data.columns = data.columns.get_level_values(0)\\n",
                "\\n",
                "if not data.empty:\\n",
                '    print(f"Fetched {len(data)} days")\\n',
                "    print(f\"Latest: RM {data['Close'].iloc[-1]:.2f}\")\\n",
                "else:\\n",
                '    print("No data")',
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 2: Measuring Trend Strength with ADX\\n",
                "\\n",
                "### What is ADX?\\n",
                "\\n",
                "**Average Directional Index (ADX)** measures trend strength (not direction).\\n",
                "\\n",
                "**Range**: 0 to 100\\n",
                "- **0-25** = Weak/No trend (ranging market)\\n",
                "- **25-50** = Strong trend\\n",
                "- **50-75** = Very strong trend\\n",
                "- **75-100** = Extremely strong trend\\n",
                "\\n",
                "### Components\\n",
                "\\n",
                "ADX has three lines:\\n",
                "- **+DI** (Positive Directional Indicator) = Upward pressure\\n",
                "- **-DI** (Negative Directional Indicator) = Downward pressure\\n",
                "- **ADX** = Strength of trend (regardless of direction)\\n",
                "\\n",
                "### How to Use ADX\\n",
                "\\n",
                "**For Trend Trading**:\\n",
                "- ADX > 25 + +DI > -DI = Trade uptrend\\n",
                "- ADX > 25 + -DI > +DI = Trade downtrend\\n",
                "- ADX < 25 = Don't trend trade (use oscillators instead)\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Calculate ADX manually\\n",
                "def calculate_adx(df, period=14):\\n",
                '    """Calculate ADX, +DI, -DI"""\\n',
                "    \\n",
                "    # True Range\\n",
                "    df['H-L'] = df['High'] - df['Low']\\n",
                "    df['H-PC'] = abs(df['High'] - df['Close'].shift(1))\\n",
                "    df['L-PC'] = abs(df['Low'] - df['Close'].shift(1))\\n",
                "    df['TR'] = df[['H-L', 'H-PC', 'L-PC']].max(axis=1)\\n",
                "    \\n",
                "    # Directional Movement\\n",
                "    df['H-PH'] = df['High'] - df['High'].shift(1)\\n",
                "    df['PL-L'] = df['Low'].shift(1) - df['Low']\\n",
                "    \\n",
                "    df['+DM'] = np.where((df['H-PH'] > df['PL-L']) & (df['H-PH'] > 0), df['H-PH'], 0)\\n",
                "    df['-DM'] = np.where((df['PL-L'] > df['H-PH']) & (df['PL-L'] > 0), df['PL-L'], 0)\\n",
                "    \\n",
                "    # Smoothed TR and DM\\n",
                "    df['TR_smooth'] = df['TR'].rolling(window=period).sum()\\n",
                "    df['+DM_smooth'] = df['+DM'].rolling(window=period).sum()\\n",
                "    df['-DM_smooth'] = df['-DM'].rolling(window=period).sum()\\n",
                "    \\n",
                "    # Directional Indicators\\n",
                "    df['+DI'] = (df['+DM_smooth'] / df['TR_smooth']) * 100\\n",
                "    df['-DI'] = (df['-DM_smooth'] / df['TR_smooth']) * 100\\n",
                "    \\n",
                "    # DX and ADX\\n",
                "    df['DX'] = (abs(df['+DI'] - df['-DI']) / (df['+DI'] + df['-DI'])) * 100\\n",
                "    df['ADX'] = df['DX'].rolling(window=period).mean()\\n",
                "    \\n",
                "    return df\\n",
                "\\n",
                "# Calculate ADX\\n",
                "if 'data' in locals() and not data.empty:\\n",
                "    data = calculate_adx(data)\\n",
                "    \\n",
                "    latest_adx = data['ADX'].iloc[-1]\\n",
                "    latest_plus_di = data['+DI'].iloc[-1]\\n",
                "    latest_minus_di = data['-DI'].iloc[-1]\\n",
                "    \\n",
                '    print("ADX Trend Strength Analysis\\\\n")\\n',
                '    print("="*60)\\n',
                '    print(f"ADX: {latest_adx:.2f}")\\n',
                '    print(f"+DI: {latest_plus_di:.2f}")\\n',
                '    print(f"-DI: {latest_minus_di:.2f}\\\\n")\\n',
                "    \\n",
                "    # Interpret\\n",
                "    if latest_adx < 25:\\n",
                '        print("WEAK TREND (ADX < 25) - Ranging market, use oscillators")\\n',
                "    elif latest_adx < 50:\\n",
                '        print("STRONG TREND (ADX 25-50) - Good for trend trading")\\n',
                "    else:\\n",
                '        print("VERY STRONG TREND (ADX > 50) - Powerful trend in place")\\n',
                "    \\n",
                "    if latest_plus_di > latest_minus_di:\\n",
                '        print(f"Direction: BULLISH (+DI > -DI)")\\n',
                "    else:\\n",
                '        print(f"Direction: BEARISH (-DI > +DI)")\\n',
                "    \\n",
                "    # Trading recommendation\\n",
                '    print("\\\\nTRADING RECOMMENDATION:")\\n',
                "    if latest_adx > 25 and latest_plus_di > latest_minus_di:\\n",
                '        print("Look for LONG positions (strong uptrend)")\\n',
                "    elif latest_adx > 25 and latest_minus_di > latest_plus_di:\\n",
                '        print("Look for SHORT positions (strong downtrend)")\\n',
                "    else:\\n",
                '        print("AVOID trend trading - Use oscillator strategies instead")',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Visualize ADX with price\\n",
                "if 'data' in locals() and 'ADX' in data.columns:\\n",
                "    recent_data = data.tail(120)\\n",
                "    \\n",
                "    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(15, 10), sharex=True)\\n",
                "    \\n",
                "    # Price chart\\n",
                "    ax1.plot(recent_data.index, recent_data['Close'], label='Close', linewidth=2, color='black')\\n",
                "    ax1.set_title(f'{ticker} - Price with ADX Trend Strength', fontsize=16, fontweight='bold')\\n",
                "    ax1.set_ylabel('Price (RM)')\\n",
                "    ax1.legend(loc='best')\\n",
                "    ax1.grid(True, alpha=0.3)\\n",
                "    \\n",
                "    # ADX chart\\n",
                "    ax2.plot(recent_data.index, recent_data['ADX'], label='ADX', linewidth=2, color='black')\\n",
                "    ax2.plot(recent_data.index, recent_data['+DI'], label='+DI', linewidth=1.5, color='green')\\n",
                "    ax2.plot(recent_data.index, recent_data['-DI'], label='-DI', linewidth=1.5, color='red')\\n",
                "    ax2.axhline(y=25, color='blue', linestyle='--', alpha=0.7, label='Trend Threshold (25)')\\n",
                "    ax2.fill_between(recent_data.index, 0, 25, alpha=0.1, color='gray')\\n",
                "    ax2.set_ylabel('ADX Value')\\n",
                "    ax2.set_xlabel('Date')\\n",
                "    ax2.legend(loc='best')\\n",
                "    ax2.grid(True, alpha=0.3)\\n",
                "    \\n",
                "    plt.tight_layout()\\n",
                "    plt.show()\\n",
                "    \\n",
                '    print("\\\\nWhen ADX is above 25, trend trading strategies work best")\\n',
                '    print("When ADX is below 25, oscillator strategies work best")',
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\\n",
                "\\n",
                "## Part 3: Common Chart Patterns\\n",
                "\\n",
                "### Continuation Patterns\\n",
                "\\n",
                "**1. Bull Flag**\\n",
                "- Strong uptrend (flagpole)\\n",
                "- Brief consolidation (flag)\\n",
                "- Breakout continues uptrend\\n",
                "- Target: Flagpole height added to breakout\\n",
                "\\n",
                "**2. Ascending Triangle**\\n",
                "- Flat resistance, rising support\\n",
                "- Bullish pattern\\n",
                "- Breakout above resistance\\n",
                "- Target: Height of triangle\\n",
                "\\n",
                "### Reversal Patterns\\n",
                "\\n",
                "**1. Head and Shoulders**\\n",
                "- Left shoulder, head, right shoulder\\n",
                "- Neckline = support\\n",
                "- Break below neckline = Sell signal\\n",
                "- Target: Head to neckline distance\\n",
                "\\n",
                "**2. Double Top**\\n",
                "- Two peaks at similar price\\n",
                "- Bearish reversal\\n",
                "- Break below valley = Sell\\n",
                "- Target: Peak to valley distance\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Key Takeaways\\n",
                "\\n",
                "### What You Learned\\n",
                "\\n",
                "1. **Chart Patterns**\\n",
                "   - Continuation patterns = trend continues\\n",
                "   - Reversal patterns = trend reverses\\n",
                "   - Patterns have measurable targets\\n",
                "\\n",
                "2. **ADX (Trend Strength)**\\n",
                "   - ADX measures strength, not direction\\n",
                "   - ADX > 25 = Use trend strategies\\n",
                "   - ADX < 25 = Use oscillator strategies\\n",
                "   - +DI vs -DI shows direction\\n",
                "\\n",
                "3. **Combining Tools**\\n",
                "   - Pattern + Strong ADX = High probability\\n",
                "   - Pattern + Weak ADX = Lower probability\\n",
                "   - Always confirm with volume\\n",
                "\\n",
                "4. **Best Practices**\\n",
                "   - Wait for pattern completion\\n",
                "   - Confirm with ADX > 25\\n",
                "   - Measure targets before entry\\n",
                "   - Use stop-loss below pattern\\n",
                "\\n",
                "---\\n",
                "\\n",
                "## Practice Exercise\\n",
                "\\n",
                "Look at the UUE chart and identify:\\n",
                "1. Current ADX value - Is trend strong?\\n",
                "2. Can you spot any patterns forming?\\n",
                "3. Are +DI and -DI aligned with price?\\n",
                "\\n",
                "Try with other stocks:\\n",
                "- 1155.KL (Maybank)\\n",
                "- 5296.KL (Tenaga)\\n",
                "\\n",
                "---\\n",
                "\\n",
                "## What's Next?\\n",
                "\\n",
                "**Module 12: Risk Management & Position Sizing**\\n",
                "\\n",
                "Learn the most important skill in trading - how to manage risk and size positions properly!\\n",
                "\\n",
                "---",
            ],
        },
    ],
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.0",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

# Save
with open("11_chart_patterns_trend_strength.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("Module 11 created successfully!")
