import json
import sys

sys.stdout.reconfigure(encoding="utf-8")

# Create Module 12: Risk Management & Position Sizing
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Module 12: Risk Management & Position Sizing\\n",
                "\\n",
                "---\\n",
                "\\n",
                "## Welcome to Module 12!\\n",
                "\\n",
                "This might be the MOST IMPORTANT module of all! You can have the best technical analysis skills, but without proper risk management, you'll lose money.\\n",
                "\\n",
                "### Learning Objectives\\n",
                "\\n",
                "- Understand the 1-2% rule\\n",
                "- Calculate position sizes based on risk\\n",
                "- Set proper stop-loss levels\\n",
                "- Manage risk-reward ratios\\n",
                "- Calculate optimal position size\\n",
                "- Understand portfolio heat\\n",
                "\\n",
                "### Prerequisites\\n",
                "\\n",
                "- Completed Modules 00-11\\n",
                "- Understanding of stop-loss concepts\\n",
                "- Basic math skills\\n",
                "\\n",
                "### Time Required: 60-75 minutes\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 1: Why Risk Management Matters\\n",
                "\\n",
                "### The Harsh Truth\\n",
                "\\n",
                "**95% of traders lose money.** The main reason? Poor risk management, not bad technical analysis!\\n",
                "\\n",
                "### Real Example\\n",
                "\\n",
                "**Trader A (No Risk Management)**:\\n",
                "- Capital: RM 10,000\\n",
                "- Loses 50% → Down to RM 5,000\\n",
                "- Needs 100% gain just to break even!\\n",
                "\\n",
                "**Trader B (Good Risk Management)**:\\n",
                "- Capital: RM 10,000\\n",
                "- Loses 10% → Down to RM 9,000\\n",
                "- Needs only 11% gain to break even\\n",
                "\\n",
                "### The Golden Rule\\n",
                "\\n",
                "**Never risk more than 1-2% of your capital on a single trade!**\\n",
                "\\n",
                "Why?\\n",
                "- Can survive 50+ losing trades in a row\\n",
                "- Keeps you in the game\\n",
                "- Prevents emotional trading\\n",
                "- Allows compounding to work\\n",
                "\\n",
                "### Real-World Analogy\\n",
                "\\n",
                "Risk management is like **car insurance**:\\n",
                "- You pay small premiums (small losses)\\n",
                "- To avoid total disaster (account blowup)\\n",
                "- You hope to never need it\\n",
                "- But you're protected when accidents happen\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Import libraries\\n",
                "import pandas as pd\\n",
                "import numpy as np\\n",
                "import matplotlib.pyplot as plt\\n",
                "import seaborn as sns\\n",
                "\\n",
                "%matplotlib inline\\n",
                "\\n",
                "try:\\n",
                "    plt.style.use('seaborn-v0_8-darkgrid')\\n",
                "except:\\n",
                "    try:\\n",
                "        plt.style.use('seaborn-darkgrid')\\n",
                "    except:\\n",
                "        plt.style.use('default')\\n",
                "\\n",
                'print("Libraries imported successfully!")',
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 2: Position Sizing Formula\\n",
                "\\n",
                "### The Formula\\n",
                "\\n",
                "**Position Size = (Account Size × Risk %) / (Entry Price - Stop Loss)**\\n",
                "\\n",
                "### Example Calculation\\n",
                "\\n",
                "- Account Size: RM 10,000\\n",
                "- Risk per trade: 2% = RM 200\\n",
                "- Entry Price: RM 1.50\\n",
                "- Stop Loss: RM 1.40\\n",
                "- Risk per share: RM 1.50 - RM 1.40 = RM 0.10\\n",
                "\\n",
                "**Position Size** = RM 200 / RM 0.10 = **2,000 shares**\\n",
                "\\n",
                "**Total Position Value** = 2,000 × RM 1.50 = RM 3,000\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Position Size Calculator\\n",
                "def calculate_position_size(account_size, risk_percent, entry_price, stop_loss):\\n",
                '    """\\n',
                "    Calculate optimal position size based on risk\\n",
                "    \\n",
                "    Parameters:\\n",
                "    - account_size: Total trading capital (RM)\\n",
                "    - risk_percent: Percentage to risk per trade (e.g., 2 for 2%)\\n",
                "    - entry_price: Planned entry price (RM)\\n",
                "    - stop_loss: Stop-loss price (RM)\\n",
                "    \\n",
                "    Returns:\\n",
                "    - Dictionary with position details\\n",
                '    """\\n',
                "    # Calculate risk amount\\n",
                "    risk_amount = account_size * (risk_percent / 100)\\n",
                "    \\n",
                "    # Calculate risk per share\\n",
                "    risk_per_share = abs(entry_price - stop_loss)\\n",
                "    \\n",
                "    # Calculate position size\\n",
                "    shares = int(risk_amount / risk_per_share)\\n",
                "    \\n",
                "    # Calculate total position value\\n",
                "    position_value = shares * entry_price\\n",
                "    \\n",
                "    # Calculate percentage of account\\n",
                "    position_percent = (position_value / account_size) * 100\\n",
                "    \\n",
                "    return {\\n",
                "        'shares': shares,\\n",
                "        'position_value': position_value,\\n",
                "        'position_percent': position_percent,\\n",
                "        'risk_amount': risk_amount,\\n",
                "        'risk_per_share': risk_per_share\\n",
                "    }\\n",
                "\\n",
                "# Example calculation\\n",
                'print("Position Size Calculator\\\\n")\\n',
                'print("="*60)\\n',
                "\\n",
                "account = 10000  # RM 10,000\\n",
                "risk = 2  # 2%\\n",
                "entry = 1.50  # RM 1.50\\n",
                "stop = 1.40  # RM 1.40\\n",
                "\\n",
                "result = calculate_position_size(account, risk, entry, stop)\\n",
                "\\n",
                'print(f"Account Size: RM {account:,.2f}")\\n',
                "print(f\"Risk per Trade: {risk}% = RM {result['risk_amount']:.2f}\")\\n",
                'print(f"Entry Price: RM {entry:.2f}")\\n',
                'print(f"Stop Loss: RM {stop:.2f}")\\n',
                "print(f\"Risk per Share: RM {result['risk_per_share']:.2f}\\\\n\")\\n",
                "\\n",
                "print(f\"POSITION SIZE: {result['shares']:,} shares\")\\n",
                "print(f\"Position Value: RM {result['position_value']:,.2f}\")\\n",
                "print(f\"Position as % of Account: {result['position_percent']:.1f}%\\\\n\")\\n",
                "\\n",
                "print(f\"Maximum Loss if Stop Hit: RM {result['risk_amount']:.2f} ({risk}% of account)\")",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 3: Risk-Reward Ratios\\n",
                "\\n",
                "### What is Risk-Reward?\\n",
                "\\n",
                "**Risk-Reward Ratio** = Potential Profit / Potential Loss\\n",
                "\\n",
                "### Minimum Requirements\\n",
                "\\n",
                "**Never take trades with less than 1:2 risk-reward!**\\n",
                "\\n",
                "**Example**:\\n",
                "- Entry: RM 1.50\\n",
                "- Stop: RM 1.40 (Risk = RM 0.10)\\n",
                "- Target: RM 1.70 (Reward = RM 0.20)\\n",
                "- Risk-Reward: 1:2 (Good!)\\n",
                "\\n",
                "### Why 1:2 or Better?\\n",
                "\\n",
                "**With 1:2 Risk-Reward**:\\n",
                "- Win rate needed: Only 33%\\n",
                "- Lose 2, win 1 = Breakeven\\n",
                "- Lose 1, win 1 = Profit!\\n",
                "\\n",
                "**With 1:1 Risk-Reward**:\\n",
                "- Win rate needed: 50%\\n",
                "- Much harder to achieve\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Risk-Reward Calculator\\n",
                "def calculate_risk_reward(entry, stop_loss, target):\\n",
                '    """Calculate risk-reward ratio"""\\n',
                "    risk = abs(entry - stop_loss)\\n",
                "    reward = abs(target - entry)\\n",
                "    ratio = reward / risk if risk > 0 else 0\\n",
                "    \\n",
                "    return {\\n",
                "        'risk': risk,\\n",
                "        'reward': reward,\\n",
                "        'ratio': ratio\\n",
                "    }\\n",
                "\\n",
                "# Example scenarios\\n",
                'print("Risk-Reward Analysis\\\\n")\\n',
                'print("="*60)\\n',
                "\\n",
                "scenarios = [\\n",
                "    {'entry': 1.50, 'stop': 1.40, 'target': 1.70, 'name': 'Good Trade'},\\n",
                "    {'entry': 1.50, 'stop': 1.40, 'target': 1.80, 'name': 'Great Trade'},\\n",
                "    {'entry': 1.50, 'stop': 1.40, 'target': 1.55, 'name': 'Bad Trade'}\\n",
                "]\\n",
                "\\n",
                "for scenario in scenarios:\\n",
                "    result = calculate_risk_reward(scenario['entry'], scenario['stop'], scenario['target'])\\n",
                "    \\n",
                "    print(f\"\\\\n{scenario['name']}:\")\\n",
                "    print(f\"  Entry: RM {scenario['entry']:.2f}\")\\n",
                "    print(f\"  Stop: RM {scenario['stop']:.2f}\")\\n",
                "    print(f\"  Target: RM {scenario['target']:.2f}\")\\n",
                "    print(f\"  Risk: RM {result['risk']:.2f}\")\\n",
                "    print(f\"  Reward: RM {result['reward']:.2f}\")\\n",
                "    print(f\"  Risk-Reward: 1:{result['ratio']:.1f}\")\\n",
                "    \\n",
                "    if result['ratio'] >= 2:\\n",
                '        print(f"  VERDICT: Acceptable (1:2 or better)")\\n',
                "    elif result['ratio'] >= 1.5:\\n",
                '        print(f"  VERDICT: Marginal (consider skipping)")\\n',
                "    else:\\n",
                '        print(f"  VERDICT: Poor (DO NOT TAKE!)")',
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 4: Portfolio Heat\\n",
                "\\n",
                "### What is Portfolio Heat?\\n",
                "\\n",
                "**Portfolio Heat** = Total risk across all open positions\\n",
                "\\n",
                "### The Rule\\n",
                "\\n",
                "**Never have more than 6% of your account at risk at once!**\\n",
                "\\n",
                "**Example**:\\n",
                "- Account: RM 10,000\\n",
                "- Max total risk: 6% = RM 600\\n",
                "- 2% per trade\\n",
                "- Maximum 3 positions open simultaneously\\n",
                "\\n",
                "### Why Limit Portfolio Heat?\\n",
                "\\n",
                "- Multiple positions can all go wrong\\n",
                "- Correlation risk (similar stocks move together)\\n",
                "- Keeps you from over-leveraging\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Portfolio Heat Calculator\\n",
                "def calculate_portfolio_heat(account_size, positions):\\n",
                '    """\\n',
                "    Calculate total portfolio risk\\n",
                "    \\n",
                "    positions = list of dicts with 'shares', 'entry', 'stop'\\n",
                '    """\\n',
                "    total_risk = 0\\n",
                "    position_details = []\\n",
                "    \\n",
                "    for i, pos in enumerate(positions, 1):\\n",
                "        risk_per_share = abs(pos['entry'] - pos['stop'])\\n",
                "        position_risk = pos['shares'] * risk_per_share\\n",
                "        total_risk += position_risk\\n",
                "        \\n",
                "        position_details.append({\\n",
                "            'position_num': i,\\n",
                "            'risk_amount': position_risk,\\n",
                "            'risk_percent': (position_risk / account_size) * 100\\n",
                "        })\\n",
                "    \\n",
                "    total_heat = (total_risk / account_size) * 100\\n",
                "    \\n",
                "    return {\\n",
                "        'total_risk': total_risk,\\n",
                "        'portfolio_heat': total_heat,\\n",
                "        'positions': position_details\\n",
                "    }\\n",
                "\\n",
                "# Example portfolio\\n",
                'print("Portfolio Heat Analysis\\\\n")\\n',
                'print("="*60)\\n',
                "\\n",
                "account = 10000\\n",
                "my_positions = [\\n",
                "    {'shares': 2000, 'entry': 1.50, 'stop': 1.40},\\n",
                "    {'shares': 1500, 'entry': 2.00, 'stop': 1.85},\\n",
                "    {'shares': 1000, 'entry': 3.00, 'stop': 2.80}\\n",
                "]\\n",
                "\\n",
                "result = calculate_portfolio_heat(account, my_positions)\\n",
                "\\n",
                'print(f"Account Size: RM {account:,}\\\\n")\\n',
                "\\n",
                "for pos in result['positions']:\\n",
                "    print(f\"Position {pos['position_num']}: RM {pos['risk_amount']:.2f} risk ({pos['risk_percent']:.1f}%)\")\\n",
                "\\n",
                "print(f\"\\\\nTOTAL PORTFOLIO HEAT: {result['portfolio_heat']:.1f}%\")\\n",
                "print(f\"Total at Risk: RM {result['total_risk']:.2f}\\\\n\")\\n",
                "\\n",
                "if result['portfolio_heat'] <= 6:\\n",
                '    print("STATUS: SAFE - Portfolio heat within limits")\\n',
                "elif result['portfolio_heat'] <= 10:\\n",
                '    print("STATUS: WARNING - Portfolio heat is high")\\n',
                "else:\\n",
                '    print("STATUS: DANGER - Portfolio heat too high! Close some positions!")',
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Key Takeaways\\n",
                "\\n",
                "### The 5 Golden Rules\\n",
                "\\n",
                "1. **Never risk more than 1-2% per trade**\\n",
                "   - Protects your account\\n",
                "   - Allows you to survive losing streaks\\n",
                "\\n",
                "2. **Use proper position sizing**\\n",
                "   - Calculate based on stop-loss distance\\n",
                '   - Not based on "gut feeling"\\n',
                "\\n",
                "3. **Minimum 1:2 risk-reward**\\n",
                "   - Only take trades with good risk-reward\\n",
                "   - Skip marginal setups\\n",
                "\\n",
                "4. **Limit portfolio heat to 6%**\\n",
                "   - Don't have too many positions at once\\n",
                "   - Maximum 3-4 positions if risking 2% each\\n",
                "\\n",
                "5. **Always use stop-losses**\\n",
                "   - Set before entering trade\\n",
                "   - Never move stop-loss further away\\n",
                "   - Honor your stops!\\n",
                "\\n",
                "### The Math of Survival\\n",
                "\\n",
                "**Risking 2% per trade:**\\n",
                "- 10 losses in a row = 18% total loss\\n",
                "- 20 losses in a row = 33% total loss\\n",
                "- Still in the game!\\n",
                "\\n",
                "**Risking 10% per trade:**\\n",
                "- 5 losses in a row = 41% total loss\\n",
                "- 10 losses in a row = 65% total loss\\n",
                "- Nearly wiped out!\\n",
                "\\n",
                "---\\n",
                "\\n",
                "## Practice Exercises\\n",
                "\\n",
                "### Exercise 1: Position Sizing\\n",
                "Calculate position size for:\\n",
                "- Account: RM 20,000\\n",
                "- Risk: 2%\\n",
                "- Entry: RM 2.50\\n",
                "- Stop: RM 2.30\\n",
                "\\n",
                "### Exercise 2: Risk-Reward\\n",
                "Is this trade acceptable?\\n",
                "- Entry: RM 1.80\\n",
                "- Stop: RM 1.70\\n",
                "- Target: RM 1.95\\n",
                "\\n",
                "### Exercise 3: Portfolio Heat\\n",
                "You have 4 positions, each risking RM 200. Account is RM 10,000.\\n",
                "What's your portfolio heat? Is it safe?\\n",
                "\\n",
                "---\\n",
                "\\n",
                "## What's Next?\\n",
                "\\n",
                "**Module 13: Multi-Stock Screening & Sector Analysis**\\n",
                "\\n",
                "Learn to scan hundreds of stocks to find the best opportunities!\\n",
                "\\n",
                "---\\n",
                "\\n",
                "**Remember: Good risk management is the difference between profitable traders and broke traders!**",
            ],
        },
    ],
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.0",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

# Save
with open("12_risk_management_position_sizing.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("Module 12 created successfully!")
