import json
import sys

sys.stdout.reconfigure(encoding="utf-8")

# Create Module 13: Multi-Stock Screening & Sector Analysis
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Module 13: Multi-Stock Screening & Sector Analysis\\n",
                "\\n",
                "---\\n",
                "\\n",
                "## Welcome to the Final Module!\\n",
                "\\n",
                "Congratulations on making it this far! In this final module, you'll learn to scan multiple stocks simultaneously and find the best trading opportunities!\\n",
                "\\n",
                "### Learning Objectives\\n",
                "\\n",
                "- Build a multi-stock screener\\n",
                "- Scan for technical signals across Malaysian stocks\\n",
                "- Analyze sector performance\\n",
                "- Create a watchlist\\n",
                "- Rank stocks by opportunity quality\\n",
                "\\n",
                "### Prerequisites\\n",
                "\\n",
                "- Completed Modules 00-12\\n",
                "- Understanding of all technical indicators\\n",
                "- Basic Python programming\\n",
                "\\n",
                "### Time Required: 75-90 minutes\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 1: Why Screen Multiple Stocks?\\n",
                "\\n",
                "### The Problem\\n",
                "\\n",
                "- Bursa Malaysia has 900+ listed stocks\\n",
                "- Manually analyzing each one is impossible\\n",
                "- You need automation to find opportunities\\n",
                "\\n",
                "### The Solution: Stock Screeners\\n",
                "\\n",
                "A **stock screener** automatically filters stocks based on technical criteria:\\n",
                "- RSI < 30 (oversold)\\n",
                "- Price above 200 SMA (uptrend)\\n",
                "- MACD bullish crossover\\n",
                "- Volume spike\\n",
                "\\n",
                "### Real-World Analogy\\n",
                "\\n",
                "Stock screening is like **online shopping filters**:\\n",
                "- You don't browse all 10,000 products\\n",
                "- You filter: price range, brand, rating, etc.\\n",
                "- Only see relevant results\\n",
                "- Same concept for stocks!\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Import libraries\\n",
                "import yfinance as yf\\n",
                "import pandas as pd\\n",
                "import numpy as np\\n",
                "import matplotlib.pyplot as plt\\n",
                "import seaborn as sns\\n",
                "import warnings\\n",
                "from datetime import datetime\\n",
                "\\n",
                "warnings.filterwarnings('ignore')\\n",
                "%matplotlib inline\\n",
                "\\n",
                "try:\\n",
                "    plt.style.use('seaborn-v0_8-darkgrid')\\n",
                "except:\\n",
                "    try:\\n",
                "        plt.style.use('seaborn-darkgrid')\\n",
                "    except:\\n",
                "        plt.style.use('default')\\n",
                "\\n",
                'print("Libraries imported successfully!")',
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 2: Building a Stock Screener\\n",
                "\\n",
                "### Popular Malaysian Stocks\\n",
                "\\n",
                "We'll screen a sample of major Malaysian stocks:\\n",
                "- **Blue Chips**: Maybank, CIMB, Tenaga, Petronas Gas\\n",
                "- **Mid Caps**: UUE, Gamuda, YTL, IOI Corp\\n",
                "- **Tech**: GHL Systems, ViTrox\\n",
                "\\n",
                "### Screening Criteria\\n",
                "\\n",
                "We'll look for:\\n",
                "1. **Trend**: Price above 50 SMA\\n",
                "2. **Momentum**: RSI between 40-70 (not extreme)\\n",
                "3. **Volume**: Above average volume\\n",
                "4. **Volatility**: ATR reasonable (not too wild)\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Define Malaysian stocks to screen\\n",
                "MALAYSIAN_STOCKS = {\\n",
                "    # Blue Chips\\n",
                "    '1155.KL': 'Maybank',\\n",
                "    '1023.KL': 'CIMB',\\n",
                "    '5296.KL': 'Tenaga',\\n",
                "    '6033.KL': 'Petronas Gas',\\n",
                "    '4715.KL': 'Genting',\\n",
                "    \\n",
                "    # Mid Caps\\n",
                "    '0310.KL': 'UUE Holdings',\\n",
                "    '5398.KL': 'Gamuda',\\n",
                "    '4677.KL': 'YTL Corp',\\n",
                "    '1961.KL': 'IOI Corp',\\n",
                "    \\n",
                "    # Tech\\n",
                "    '0021.KL': 'GHL Systems',\\n",
                "    '0097.KL': 'ViTrox'\\n",
                "}\\n",
                "\\n",
                'print(f"Screening {len(MALAYSIAN_STOCKS)} Malaysian stocks...")\\n',
                'print("\\\\nStocks in screening list:")\\n',
                "for ticker, name in MALAYSIAN_STOCKS.items():\\n",
                '    print(f"  {ticker}: {name}")',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Stock analysis function\\n",
                "def analyze_stock(ticker):\\n",
                '    """Analyze a single stock for technical signals"""\\n',
                "    try:\\n",
                "        # Download data\\n",
                "        data = yf.download(ticker, period='6mo', progress=False)\\n",
                "        \\n",
                "        if isinstance(data.columns, pd.MultiIndex):\\n",
                "            data.columns = data.columns.get_level_values(0)\\n",
                "        \\n",
                "        if data.empty or len(data) < 50:\\n",
                "            return None\\n",
                "        \\n",
                "        # Calculate indicators\\n",
                "        data['SMA_50'] = data['Close'].rolling(window=50).mean()\\n",
                "        data['SMA_200'] = data['Close'].rolling(window=200).mean()\\n",
                "        \\n",
                "        # RSI\\n",
                "        delta = data['Close'].diff()\\n",
                "        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()\\n",
                "        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()\\n",
                "        rs = gain / loss\\n",
                "        data['RSI'] = 100 - (100 / (1 + rs))\\n",
                "        \\n",
                "        # Volume analysis\\n",
                "        data['Vol_SMA_20'] = data['Volume'].rolling(window=20).mean()\\n",
                "        \\n",
                "        # Get latest values\\n",
                "        latest = data.iloc[-1]\\n",
                "        \\n",
                "        # Calculate signals\\n",
                "        price = latest['Close']\\n",
                "        sma_50 = latest['SMA_50']\\n",
                "        rsi = latest['RSI']\\n",
                "        volume = latest['Volume']\\n",
                "        avg_volume = latest['Vol_SMA_20']\\n",
                "        \\n",
                "        # Trend signal\\n",
                "        trend_signal = 'BULLISH' if pd.notna(sma_50) and price > sma_50 else 'BEARISH'\\n",
                "        \\n",
                "        # Momentum signal\\n",
                "        if pd.notna(rsi):\\n",
                "            if rsi < 30:\\n",
                "                momentum_signal = 'OVERSOLD'\\n",
                "            elif rsi > 70:\\n",
                "                momentum_signal = 'OVERBOUGHT'\\n",
                "            elif 40 <= rsi <= 60:\\n",
                "                momentum_signal = 'NEUTRAL'\\n",
                "            else:\\n",
                "                momentum_signal = 'TRENDING'\\n",
                "        else:\\n",
                "            momentum_signal = 'N/A'\\n",
                "        \\n",
                "        # Volume signal\\n",
                "        volume_signal = 'HIGH' if volume > avg_volume else 'NORMAL'\\n",
                "        \\n",
                "        # Overall score (0-100)\\n",
                "        score = 0\\n",
                "        if trend_signal == 'BULLISH': score += 40\\n",
                "        if momentum_signal in ['NEUTRAL', 'TRENDING']: score += 30\\n",
                "        if momentum_signal == 'OVERSOLD': score += 20  # Buying opportunity\\n",
                "        if volume_signal == 'HIGH': score += 20\\n",
                "        if pd.notna(rsi) and 45 <= rsi <= 55: score += 10  # Sweet spot\\n",
                "        \\n",
                "        return {\\n",
                "            'ticker': ticker,\\n",
                "            'price': price,\\n",
                "            'sma_50': sma_50,\\n",
                "            'rsi': rsi,\\n",
                "            'volume_ratio': volume / avg_volume if avg_volume > 0 else 0,\\n",
                "            'trend': trend_signal,\\n",
                "            'momentum': momentum_signal,\\n",
                "            'volume_signal': volume_signal,\\n",
                "            'score': min(score, 100)  # Cap at 100\\n",
                "        }\\n",
                "    \\n",
                "    except Exception as e:\\n",
                '        print(f"Error analyzing {ticker}: {str(e)}")\\n',
                "        return None\\n",
                "\\n",
                "# Screen all stocks\\n",
                'print("\\\\nScreening stocks (this may take a minute)...\\\\n")\\n',
                "results = []\\n",
                "\\n",
                "for ticker, name in MALAYSIAN_STOCKS.items():\\n",
                '    print(f"Analyzing {ticker} ({name})...")\\n',
                "    result = analyze_stock(ticker)\\n",
                "    if result:\\n",
                "        result['name'] = name\\n",
                "        results.append(result)\\n",
                "\\n",
                "# Create DataFrame\\n",
                "df_results = pd.DataFrame(results)\\n",
                "\\n",
                "# Sort by score\\n",
                "df_results = df_results.sort_values('score', ascending=False)\\n",
                "\\n",
                'print(f"\\\\nSuccessfully analyzed {len(df_results)} stocks!")',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Display screening results\\n",
                'print("Stock Screening Results\\\\n")\\n',
                'print("="*80)\\n',
                "\\n",
                "# Format for display\\n",
                "display_df = df_results[['ticker', 'name', 'price', 'rsi', 'trend', 'momentum', 'score']].copy()\\n",
                "display_df['price'] = display_df['price'].apply(lambda x: f\"RM {x:.2f}\")\\n",
                "display_df['rsi'] = display_df['rsi'].apply(lambda x: f\"{x:.1f}\" if pd.notna(x) else 'N/A')\\n",
                "\\n",
                "print(display_df.to_string(index=False))\\n",
                'print("\\\\n" + "="*80)\\n',
                "\\n",
                "# Top opportunities\\n",
                'print("\\\\nTOP 3 OPPORTUNITIES:")\\n',
                "for i, row in df_results.head(3).iterrows():\\n",
                "    print(f\"\\\\n{row['ticker']} - {row['name']}\")\\n",
                "    print(f\"  Score: {row['score']}/100\")\\n",
                "    print(f\"  Price: RM {row['price']:.2f}\")\\n",
                "    print(f\"  Trend: {row['trend']}\")\\n",
                "    print(f\"  RSI: {row['rsi']:.1f}\" if pd.notna(row['rsi']) else \"  RSI: N/A\")\\n",
                "    print(f\"  Momentum: {row['momentum']}\")\\n",
                "    print(f\"  Volume: {row['volume_signal']}\")",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Visualize screening results\\n",
                "if len(df_results) > 0:\\n",
                "    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))\\n",
                "    \\n",
                "    # Bar chart of scores\\n",
                "    colors = ['green' if score >= 70 else 'orange' if score >= 50 else 'red' \\n",
                "              for score in df_results['score']]\\n",
                "    \\n",
                "    ax1.barh(df_results['ticker'], df_results['score'], color=colors)\\n",
                "    ax1.set_xlabel('Opportunity Score')\\n",
                "    ax1.set_title('Stock Screening Scores', fontweight='bold')\\n",
                "    ax1.axvline(x=70, color='green', linestyle='--', alpha=0.5, label='Good (70+)')\\n",
                "    ax1.axvline(x=50, color='orange', linestyle='--', alpha=0.5, label='Fair (50+)')\\n",
                "    ax1.legend()\\n",
                "    ax1.grid(True, alpha=0.3)\\n",
                "    \\n",
                "    # Scatter: RSI vs Score\\n",
                "    valid_rsi = df_results[df_results['rsi'].notna()]\\n",
                "    ax2.scatter(valid_rsi['rsi'], valid_rsi['score'], s=100, alpha=0.6)\\n",
                "    \\n",
                "    for _, row in valid_rsi.iterrows():\\n",
                "        ax2.annotate(row['ticker'].replace('.KL', ''), \\n",
                "                    (row['rsi'], row['score']), \\n",
                "                    fontsize=8, ha='right')\\n",
                "    \\n",
                "    ax2.axhline(y=70, color='green', linestyle='--', alpha=0.3)\\n",
                "    ax2.axhline(y=50, color='orange', linestyle='--', alpha=0.3)\\n",
                "    ax2.axvline(x=30, color='green', linestyle='--', alpha=0.3, label='Oversold')\\n",
                "    ax2.axvline(x=70, color='red', linestyle='--', alpha=0.3, label='Overbought')\\n",
                "    ax2.set_xlabel('RSI')\\n",
                "    ax2.set_ylabel('Score')\\n",
                "    ax2.set_title('RSI vs Opportunity Score', fontweight='bold')\\n",
                "    ax2.legend()\\n",
                "    ax2.grid(True, alpha=0.3)\\n",
                "    \\n",
                "    plt.tight_layout()\\n",
                "    plt.show()\\n",
                "    \\n",
                '    print("\\\\nGreen = Strong opportunity (70+)")\\n',
                '    print("Orange = Moderate opportunity (50-70)")\\n',
                '    print("Red = Weak opportunity (<50)")',
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\\n",
                "\\n",
                "## Part 3: Building Your Watchlist\\n",
                "\\n",
                "### How to Use Screening Results\\n",
                "\\n",
                "1. **Top Scorers (70+)**\\n",
                "   - Add to immediate watchlist\\n",
                "   - Perform detailed analysis\\n",
                "   - Look for entry points\\n",
                "\\n",
                "2. **Moderate Scores (50-70)**\\n",
                "   - Monitor for improvement\\n",
                "   - Wait for better setup\\n",
                "\\n",
                "3. **Low Scores (<50)**\\n",
                "   - Skip for now\\n",
                "   - Re-screen later\\n",
                "\\n",
                "### Daily Routine\\n",
                "\\n",
                "**Professional traders screen stocks daily:**\\n",
                "1. Run screener before market opens\\n",
                "2. Identify top 3-5 opportunities\\n",
                "3. Analyze in detail\\n",
                "4. Set price alerts\\n",
                "5. Wait for entry signals\\n",
                "\\n",
                "---",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Key Takeaways\\n",
                "\\n",
                "### What You Learned\\n",
                "\\n",
                "1. **Stock Screening**\\n",
                "   - Automates finding opportunities\\n",
                "   - Filters by technical criteria\\n",
                "   - Saves hours of manual work\\n",
                "\\n",
                "2. **Screening Criteria**\\n",
                "   - Trend (SMA position)\\n",
                "   - Momentum (RSI levels)\\n",
                "   - Volume (relative to average)\\n",
                "   - Combine multiple factors\\n",
                "\\n",
                "3. **Scoring System**\\n",
                "   - Objective ranking\\n",
                "   - Focus on top opportunities\\n",
                "   - Ignore weak setups\\n",
                "\\n",
                "4. **Best Practices**\\n",
                "   - Screen daily\\n",
                "   - Focus on top 3-5 stocks\\n",
                "   - Still perform detailed analysis\\n",
                "   - Update watchlist regularly\\n",
                "\\n",
                "---\\n",
                "\\n",
                "## Congratulations!\\n",
                "\\n",
                "### You've Completed All 14 Modules!\\n",
                "\\n",
                "**From Beginner (Modules 00-06)**:\\n",
                "- Setup and basic concepts\\n",
                "- Price charts and candlesticks\\n",
                "- Moving averages\\n",
                "- RSI and MACD\\n",
                "- Volume analysis\\n",
                "- Putting it together\\n",
                "\\n",
                "**To Intermediate (Modules 07-13)**:\\n",
                "- Bollinger Bands & volatility\\n",
                "- Advanced oscillators\\n",
                "- Fibonacci retracements\\n",
                "- Multi-timeframe analysis\\n",
                "- Chart patterns & ADX\\n",
                "- Risk management\\n",
                "- Multi-stock screening\\n",
                "\\n",
                "### What's Next?\\n",
                "\\n",
                "1. **Practice, Practice, Practice**\\n",
                "   - Use paper trading first\\n",
                "   - Test strategies\\n",
                "   - Build confidence\\n",
                "\\n",
                "2. **Develop Your System**\\n",
                "   - Combine your favorite indicators\\n",
                "   - Create a trading plan\\n",
                "   - Backtest thoroughly\\n",
                "\\n",
                "3. **Start Small**\\n",
                "   - Real money with tiny positions\\n",
                "   - Follow your risk rules\\n",
                "   - Track every trade\\n",
                "\\n",
                "4. **Never Stop Learning**\\n",
                "   - Markets evolve\\n",
                "   - Keep studying\\n",
                "   - Join trading communities\\n",
                "\\n",
                "---\\n",
                "\\n",
                "## Final Words\\n",
                "\\n",
                "**Remember:**\\n",
                "- Technical analysis is a tool, not a crystal ball\\n",
                "- Risk management is MORE important than finding perfect entries\\n",
                "- Consistency beats home runs\\n",
                "- Psychology matters as much as technique\\n",
                "- **NEVER invest money you can't afford to lose**\\n",
                "\\n",
                "### Good luck on your trading journey!\\n",
                "\\n",
                "**Disclaimer**: This course is for educational purposes only. Always do your own research and consult with licensed financial advisors before making investment decisions.\\n",
                "\\n",
                "---\\n",
                "\\n",
                "**Thank you for learning with us!**",
            ],
        },
    ],
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.0",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

# Save
with open("13_multi_stock_screening.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("Module 13 created successfully!")
print("\\n*** ALL 7 INTERMEDIATE MODULES CREATED! ***")
